ARG DENO_VERSION

FROM hayd/deno-lambda:${DENO_VERSION}

# Recursively download, compile, and cache remote dependencies. Note that these
# lines only run when deps.ts changes due to the way that Docker caches layers.
COPY deps.ts .
RUN deno cache deps.ts

# Copy and pre-compile all other source files. We do not want to do this above,
# as any changes to these files would cause the dependency layers to be rebuilt.
COPY main.ts .
RUN deno cache main.ts

CMD ["main.handler"]
